# Generated by Django 4.2.6 on 2023-10-31 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(default='', editable=False, max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='Publish date')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_name', models.CharField(default='', editable=False, max_length=200)),
                ('cont_email', models.CharField(default='', editable=False, max_length=200)),
                ('query', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='EducationCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('insititute', models.CharField(max_length=100)),
                ('year_date', models.DateTimeField(verbose_name='Year')),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('about_project', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clinet_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=300)),
                ('stasified_with_work', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=100)),
                ('work_date', models.DateTimeField(verbose_name='Join date')),
                ('for_position', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='currently_work_as',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='email_id',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='home_address',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='mob_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='work_address',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='tag_line',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_skills', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=70)),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
    ]
