# Generated by Django 4.2.6 on 2023-11-01 08:22

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_blog_contact_educationcertificate_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cont_email',
            field=models.CharField(default=timezone.now(), max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cont_name',
            field=models.CharField(default=timezone.now(), max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='currently_work_as',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='tag_line',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
