# Generated by Django 4.2.6 on 2023-11-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_blog_blog_title_alter_blog_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='myBlog',
        ),
    ]
