# Generated by Django 4.2.6 on 2023-11-02 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_blog_myblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_com',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
        migrations.AddField(
            model_name='educationcertificate',
            name='Education',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
        migrations.AddField(
            model_name='myblog',
            name='blog',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='testmo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
        migrations.AddField(
            model_name='work',
            name='work',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cont_email',
            field=models.CharField(default='Ram', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cont_name',
            field=models.CharField(default='Ram', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='my_skills',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
