# Generated by Django 4.2.6 on 2023-11-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_contact_contact_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcertificate',
            name='Education',
            field=models.ForeignKey(default='Education', on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
    ]
