# Generated by Django 4.2.6 on 2023-11-02 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_educationcertificate_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='blog',
            field=models.ForeignKey(default='Blog', on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio',
            field=models.ForeignKey(default='Portfolio', on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='testmo',
            field=models.ForeignKey(default='Testmonials', on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work',
            field=models.ForeignKey(default='Work', on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
    ]
