# Generated by Django 4.2.6 on 2023-11-02 12:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_contactform_alter_portfolio_about_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='blog',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
