# Generated by Django 4.2.6 on 2023-11-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_myblog_content_alter_myblog_blog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='cont_email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='query',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='cont_name',
            new_name='Name',
        ),
    ]
