# Generated by Django 4.2.6 on 2023-11-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_cont_email_contactform_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo_pic',
            field=models.ImageField(default=0, height_field=30, upload_to='website/images', width_field=30),
        ),
    ]
