# Generated by Django 4.2.6 on 2023-11-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_user_logo_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo_pic',
            field=models.ImageField(default='Logo', height_field=30, upload_to='website/images', width_field=30),
        ),
    ]
