# Generated by Django 4.2.6 on 2023-11-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_user_logo_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo_pic',
            field=models.ImageField(default='Logo', upload_to='website/images'),
        ),
    ]
