# Generated by Django 4.2.6 on 2023-11-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_user_logo_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_pic', models.ImageField(default='Logo', upload_to='myimage')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='logo_pic',
        ),
    ]
